# flake8: noqa

"""
    Cape of Good Place Names Service

    This is a stateless service for performing various geotranslation operations, moving between how people describe places and codified coordinate systems.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: opmdata+cogpn-support@capetown.gov.za
    Generated by: https://openapi-generator.tech
"""


__version__ = "0.1.0"

# import ApiClient
from cape_of_good_place_names_client.api_client import ApiClient

# import Configuration
from cape_of_good_place_names_client.configuration import Configuration

# import exceptions
from cape_of_good_place_names_client.exceptions import OpenApiException
from cape_of_good_place_names_client.exceptions import ApiAttributeError
from cape_of_good_place_names_client.exceptions import ApiTypeError
from cape_of_good_place_names_client.exceptions import ApiValueError
from cape_of_good_place_names_client.exceptions import ApiKeyError
from cape_of_good_place_names_client.exceptions import ApiException
