# coding: utf-8

"""
    Cape of Good Place Names Service

    This is a stateless service for performing various geotranslation operations, moving between how people describe places and codified coordinate systems.  # noqa: E501

    OpenAPI spec version: 0.1.0
    Contact: opmdata+cogpn-support@capetown.gov.za
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cape_of_good_place_names_client
from cape_of_good_place_names_client.api.default_api import DefaultApi  # noqa: E501
from cape_of_good_place_names_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geocode(self):
        """Test case for geocode

        Translate a free form address into a spatial coordinate  # noqa: E501
        """
        pass

    def test_geolookup(self):
        """Test case for geolookup

        Translate a spatial identifier into a description of space  # noqa: E501
        """
        pass

    def test_scrub(self):
        """Test case for scrub

        Extract meaningful phrases or identifiers from free form addresses  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
